HRINT-2695  - IndexCompareExchange as java
ravendb/demo pull request #128
Opened 2022-05-02 14:15 UTC by Drorlev

IndexCompareExchange as java

2022-05-02 14:15 UTC, Drorlev commented
This is just the code

2022-05-02 14:16 UTC, ml054 commented on DemoServer/AdditionalLanguages/java/src/main/java/net/ravendb/demo/compareExchange/indexCompareExchange/IndexCompareExchange.java
> +            /*
?

2022-05-03 09:38 UTC, Drorlev commented
Ready for full review

2022-05-04 05:36 UTC, ml054 approved these changes

2022-05-08 14:15 UTC, Danielle9897 requested changes

2022-05-08 14:15 UTC, Danielle9897 commented on DemoServer/AdditionalLanguages/java/src/main/java/net/ravendb/demo/compareExchange/indexCompareExchange/metadata.json
> +                }
all above 3 links go to C#
pls fix

2022-05-11 10:58 UTC, Drorlev commented on DemoServer/AdditionalLanguages/java/src/main/java/net/ravendb/demo/compareExchange/indexCompareExchange/IndexCompareExchange.java
> +            /*
Done

2022-05-15 18:48 UTC, Danielle9897 requested changes

2022-05-15 18:48 UTC, Danielle9897 commented on DemoServer/AdditionalLanguages/java/src/main/java/net/ravendb/demo/compareExchange/indexCompareExchange/IndexCompareExchange.java
> +            //endregion
align with `//region demo`

2022-05-15 18:48 UTC, Danielle9897 commented on DemoServer/AdditionalLanguages/java/src/main/java/net/ravendb/demo/compareExchange/indexCompareExchange/metadata.json
> +            "Url": "/java/compare-exchange/create-compare-exchange"
align all `':'`

2022-07-03 17:04 UTC, Danielle9897 commented on DemoServer/AdditionalLanguages/java/src/main/java/net/ravendb/demo/compareExchange/indexCompareExchange/metadata.json
> +                }
this is done

2022-07-03 17:04 UTC, Danielle9897 commented on DemoServer/AdditionalLanguages/java/src/main/java/net/ravendb/demo/compareExchange/indexCompareExchange/IndexCompareExchange.java
> +            //endregion
done

2022-07-03 17:08 UTC, Danielle9897 commented on DemoServer/AdditionalLanguages/java/src/main/java/net/ravendb/demo/compareExchange/indexCompareExchange/metadata.json
> +            "Url": "/java/compare-exchange/create-compare-exchange"
done

2022-07-04 07:25 UTC, Danielle9897 approved these changes

2022-07-04 07:26 UTC, Danielle9897 commented
@ml054 this can be merged

2022-07-04 09:35 UTC, merged