HRINT-2697 - FTS Query - Using Wildcards
ravendb/demo pull request #129
Opened 2022-05-03 11:37 UTC by Drorlev

FTS Query - Using Wildcards

2022-05-04 05:37 UTC, ml054 approved these changes

2022-05-08 12:11 UTC, Danielle9897 requested changes

2022-05-08 12:11 UTC, Danielle9897 commented on DemoServer/AdditionalLanguages/java/src/main/java/net/ravendb/demo/textSearch/fTSQuerySearchWildcards/metadata.json
> +                "* Execute the query by calling `ToList()`.",
ToList() => toList()

2022-05-08 12:11 UTC, Danielle9897 commented on DemoServer/AdditionalLanguages/java/src/main/java/net/ravendb/demo/textSearch/fTSQuerySearchWildcards/metadata.json
> +                }
Are the above 2 links working ? 
or do you want to add 'TODO' here for them, as was done in walkthrough step number 3 ?

2022-05-11 09:29 UTC, Drorlev commented on DemoServer/AdditionalLanguages/java/src/main/java/net/ravendb/demo/textSearch/fTSQuerySearchWildcards/metadata.json
> +                "* Execute the query by calling `ToList()`.",
Done

2022-05-15 18:42 UTC, Danielle9897 requested changes

2022-05-15 18:42 UTC, Danielle9897 commented on DemoServer/AdditionalLanguages/java/src/main/java/net/ravendb/demo/textSearch/fTSQuerySearchWildcards/metadata.json
> +            "Url": "/java/text-search/fts-query-search-basics"
As discussed, align the `':'`

2022-05-15 18:42 UTC, Danielle9897 commented on DemoServer/AdditionalLanguages/java/src/main/java/net/ravendb/demo/demos.json
> +            "fTSWithStaticIndexSingleField",            "fTSWithStaticIndexMultipleFields"
why on the same line ?

2022-05-15 18:42 UTC, Danielle9897 commented on DemoServer/AdditionalLanguages/java/src/main/java/net/ravendb/demo/textSearch/fTSQuerySearchWildcards/metadata.json
> +                }
@Drorlev 
For the future:
Pls write `'done'` for any comment when you apply the fix.

2022-07-04 06:40 UTC, Danielle9897 commented on DemoServer/AdditionalLanguages/java/src/main/java/net/ravendb/demo/textSearch/fTSQuerySearchWildcards/metadata.json
> +            "Url": "/java/text-search/fts-query-search-basics"
done

2022-07-04 06:42 UTC, Danielle9897 commented on DemoServer/AdditionalLanguages/java/src/main/java/net/ravendb/demo/demos.json
> +            "fTSWithStaticIndexSingleField",            "fTSWithStaticIndexMultipleFields"
done

2022-07-04 07:21 UTC, Danielle9897 approved these changes

2022-07-04 07:22 UTC, Danielle9897 commented
@ml054 this can be merged

2022-07-04 09:13 UTC, merged