HRINT-2432  [Demo] Queries: Faceted Search
ravendb/demo pull request #93
Opened 2022-01-16 13:16 UTC by Danielle9897

2022-01-16 13:30 UTC, Danielle9897 commented
@DejanMilicic can you pls review ?

2022-01-23 18:14 UTC, DejanMilicic requested changes

2022-01-23 21:16 UTC, Danielle9897 commented on DemoServer/Controllers/Demos/FacetedSearch/FacetsAggregations/FacetsAggregationsController.cs
> +        public class Products_ByCategoryPriceAndUnits : AbstractIndexCreationTask<Product, Products_ByCategoryPriceAndUnits.IndexEntry>
No specific conventions that I know about...

If I look for example at an **auto-index** generated it looks like this:
`Auto/Companies/ByContactAndExternalIdAndFaxAndNameAndPhone`

I wonder what is best for this **static index:**
1. Products/ByCategoryPriceAndUnits
2. Products/ByCategory/ByPrice/ByUnits
3. Products/ByCategoryAndPriceAndUnits
4. Products/ByCategory/Price/Units

?

2022-01-23 21:38 UTC, Danielle9897 commented on DemoServer/Controllers/Demos/FacetedSearch/FacetsBasic/metadata.json
> +                "  A separated aggregated item will be created per range defined.",
done

2022-01-23 21:43 UTC, Danielle9897 commented on DemoServer/Controllers/Demos/FacetedSearch/FacetsFromDocument/metadata.json
> +            "Title": "Define class FacetSetup",
done

2022-01-23 21:44 UTC, Danielle9897 commented on DemoServer/Controllers/Demos/FacetedSearch/FacetsFromDocument/metadata.json
> +            "Title": "Store the Facet document",
done

2022-01-23 21:45 UTC, Danielle9897 commented on DemoServer/Controllers/Demos/FacetedSearch/FacetsFromDocument/metadata.json
> +                "* The setup will be stored in a document with the specified ID under the `FacetSetup` collection."
done

2022-01-23 21:45 UTC, Danielle9897 commented on DemoServer/Controllers/Demos/FacetedSearch/FacetsFromDocument/metadata.json
> +            "Title": "execute the query",
Fixed

2022-01-23 21:48 UTC, Danielle9897 commented on DemoServer/Controllers/Demos/FacetedSearch/FacetsFromDocument/metadata.json
> +                "* _Id_ - Provide the document ID in which the facet setup will be stored",
done

2022-01-23 21:49 UTC, Danielle9897 commented on DemoServer/Controllers/Demos/FacetedSearch/FacetsFromDocument/metadata.json
> +                "  Pass the facets document ID to the `AggregateUsing()` method and execute the query.",
done

2022-01-23 22:08 UTC, Danielle9897 commented on DemoServer/Controllers/Demos/FacetedSearch/FacetsFromDocument/FacetsFromDocumentController.cs
> +                    Id = "myFacetSetupDocumentID",
![image](https://user-images.githubusercontent.com/17376974/150699801-3d16e8b3-1c20-419b-8dfe-429fc006781f.png)

2022-01-23 22:46 UTC, DejanMilicic commented on DemoServer/Controllers/Demos/FacetedSearch/FacetsAggregations/FacetsAggregationsController.cs
> +        public class Products_ByCategoryPriceAndUnits : AbstractIndexCreationTask<Product, Products_ByCategoryPriceAndUnits.IndexEntry>
Let's leave it like it is

2022-01-27 08:11 UTC, DejanMilicic approved these changes

2022-01-27 08:40 UTC, merged